---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dunge-in
spec:
  replicas: 1
  selector:
    matchLabels:
      name: dunge-in
  template:
    metadata:
      labels:
        name: dunge-in
    spec:
      containers:
      - name: application
        image: localhost:32000/dunge-in
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3000
